"""Independent decision states captured from user-reviewed JanQ play."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


DecisionKind = Literal["area", "discard"]


@dataclass(frozen=True)
class StrategyReviewCase:
    case_id: str
    title: str
    source: str
    kind: DecisionKind
    hand: tuple[int, ...]
    balls: int
    forbidden_choices: tuple[int, ...]
    accepted_choices: tuple[int, ...] = ()
    drawn_tile: int | None = None
    is_reach: bool = False
    dora_id: int | None = None
    ura_dora_id: int | None = None
    objection: str = ""
    rule: str = ""


REVIEW_REGRESSION_CASES: tuple[StrategyReviewCase, ...] = (
    StrategyReviewCase(
        case_id="actual-2631-area",
        title="七张万字应进入小万字混一色路线",
        source="janq_bot_20260614_013302 line 2631",
        dora_id=19,
        ura_dora_id=12,
        kind="area",
        hand=(0, 0, 1, 2, 3, 4, 7, 15, 19, 23, 26, 31, 32),
        balls=8,
        forbidden_choices=(6,),
        accepted_choices=(1,),
        objection="万字已有七张且球数充足，不能继续按宽泛普通进张选择区域6。",
        rule="强侧路线成立时，区域选择应服从目标花色与关联字牌。",
    ),
    StrategyReviewCase(
        case_id="actual-2649-discard",
        title="不打中区时先切无关三元牌",
        source="janq_bot_20260614_013302 line 2649",
        dora_id=19,
        ura_dora_id=12,
        kind="discard",
        hand=(0, 0, 1, 2, 3, 4, 7, 15, 19, 23, 26, 31, 32, 21),
        balls=7,
        drawn_tile=21,
        forbidden_choices=(26,),
        accepted_choices=(31, 32),
        objection="9饼仍可能在后续侧区重合，白发在不打中区时更弱。",
        rule="未来区域无法支持的孤张三元牌优先退出。",
    ),
    StrategyReviewCase(
        case_id="actual-2697-discard",
        title="万字侧路线保留可能歪到的7索",
        source="janq_bot_20260614_013302 line 2697",
        dora_id=19,
        ura_dora_id=12,
        kind="discard",
        hand=(0, 0, 1, 2, 3, 4, 7, 15, 19, 21, 23, 23, 31, 8),
        balls=5,
        drawn_tile=8,
        forbidden_choices=(15,),
        accepted_choices=(31,),
        objection="白不受计划区域支持，7索仍可能被相邻区域带入。",
        rule="比较孤张时必须计入下一计划区域的歪入概率。",
    ),
    StrategyReviewCase(
        case_id="actual-2721-discard",
        title="万字路线保留东并切白",
        source="janq_bot_20260614_013302 line 2721",
        dora_id=19,
        ura_dora_id=12,
        kind="discard",
        hand=(0, 0, 1, 2, 3, 4, 7, 8, 19, 21, 23, 23, 31, 27),
        balls=4,
        drawn_tile=27,
        forbidden_choices=(27,),
        accepted_choices=(31,),
        objection="东与小万字区域强相关，白在放弃三元路线后无关。",
        rule="侧区关联字牌优先级高于无关三元孤张。",
    ),
    StrategyReviewCase(
        case_id="actual-3153-discard",
        title="区域2计划下切白而非3饼",
        source="janq_bot_20260614_013302 line 3153",
        dora_id=3,
        ura_dora_id=13,
        kind="discard",
        hand=(1, 1, 6, 8, 9, 10, 10, 13, 20, 27, 28, 29, 31, 5),
        balls=7,
        drawn_tile=5,
        forbidden_choices=(20,),
        accepted_choices=(31,),
        objection="3饼可能被后续区域歪入，白在不打中区时没有支持。",
        rule="无关三元孤张不能压过未来区域可支持的数牌。",
    ),
    StrategyReviewCase(
        case_id="actual-3651-discard",
        title="饼子北路线先切白发",
        source="janq_bot_20260614_013302 line 3651",
        dora_id=17,
        ura_dora_id=16,
        kind="discard",
        hand=(12, 14, 17, 18, 22, 22, 23, 24, 26, 27, 30, 31, 32, 30),
        balls=7,
        drawn_tile=30,
        forbidden_choices=(17,),
        accepted_choices=(31, 32),
        objection="9索可能被饼子侧区歪入，白发不属于该路线。",
        rule="侧路线先清理不受区域支持的三元孤张。",
    ),
    StrategyReviewCase(
        case_id="actual-3845-discard",
        title="饼子北路线切白而非南",
        source="janq_bot_20260614_013302 line 3845",
        dora_id=28,
        ura_dora_id=22,
        kind="discard",
        hand=(1, 3, 14, 16, 18, 19, 21, 21, 22, 26, 28, 30, 31, 30),
        balls=7,
        drawn_tile=30,
        forbidden_choices=(28,),
        accepted_choices=(31,),
        objection="白没有区域支持，南仍比白更可能形成后续价值。",
        rule="路线无关的三元孤张优先退出。",
    ),
    StrategyReviewCase(
        case_id="actual-3869-discard",
        title="饼子路线不能切索子桥接牌",
        source="janq_bot_20260614_013302 line 3869",
        dora_id=28,
        ura_dora_id=22,
        kind="discard",
        hand=(1, 3, 14, 16, 18, 19, 21, 21, 22, 26, 30, 30, 31, 24),
        balls=6,
        drawn_tile=24,
        forbidden_choices=(16,),
        objection="打小饼区域可能歪到索子，主动不打万字时弱万字或无关字牌更差。",
        rule="跨花色比较必须考虑下一计划区域的歪入支持。",
    ),
    StrategyReviewCase(
        case_id="actual-4695-area",
        title="白对白且球数充足时冲大三元",
        source="janq_bot_20260614_013302 line 4695",
        dora_id=0,
        ura_dora_id=26,
        kind="area",
        hand=(3, 6, 9, 10, 12, 13, 14, 17, 22, 23, 25, 31, 31),
        balls=8,
        forbidden_choices=(7,),
        accepted_choices=(4,),
        objection="外部已有面子和白对白，八球足以尝试补齐三元牌。",
        rule="大三元起手条件满足且球数可行时，役满路线优先。",
    ),
    StrategyReviewCase(
        case_id="actual-4785-discard",
        title="大饼侧路线拆弱12索",
        source="janq_bot_20260614_013302 line 4785",
        dora_id=0,
        ura_dora_id=26,
        kind="discard",
        hand=(9, 10, 12, 13, 14, 22, 23, 24, 25, 26, 30, 31, 31, 26),
        balls=4,
        drawn_tile=26,
        forbidden_choices=(30,),
        accepted_choices=(9, 10),
        objection="12索只等低概率3索，大饼与北可通过区域7快速形成更强听牌。",
        rule="球数足够时允许拆弱搭子，换取高概率侧区改良。",
    ),
    StrategyReviewCase(
        case_id="actual-4809-discard",
        title="三球时仍应拆弱12索",
        source="janq_bot_20260614_013302 line 4809",
        dora_id=0,
        ura_dora_id=26,
        kind="discard",
        hand=(9, 10, 12, 13, 14, 22, 23, 24, 25, 26, 26, 31, 31, 23),
        balls=3,
        drawn_tile=23,
        forbidden_choices=(26,),
        accepted_choices=(9, 10),
        objection="不能拆大饼形状继续死守低概率3索。",
        rule="比较搭子时使用最佳区域的实际完成概率。",
    ),
    StrategyReviewCase(
        case_id="random-1-turn-5-discard",
        title="普通效率阶段不得拆789饼面子",
        source="random replay sample 1 turn 5",
        dora_id=28,
        ura_dora_id=10,
        kind="discard",
        hand=(3, 5, 6, 6, 9, 11, 11, 12, 16, 16, 24, 25, 26, 11),
        balls=4,
        drawn_tile=11,
        forbidden_choices=(24, 25, 26),
        accepted_choices=(12,),
        objection="已无特殊役种路线，不能为了下一区域得分拆掉完成面子。",
        rule="普通路线按形状与向听优先；完整顺子先于区域命中率保护。",
    ),
    StrategyReviewCase(
        case_id="random-2-turn-3-discard",
        title="不得拆24446索中的暗刻",
        source="random replay sample 2 turn 3",
        dora_id=8,
        ura_dora_id=29,
        kind="discard",
        hand=(3, 5, 10, 12, 12, 14, 21, 22, 26, 28, 28, 28, 29, 12),
        balls=7,
        drawn_tile=12,
        forbidden_choices=(12,),
        accepted_choices=(3, 5, 26, 29),
        objection="24446索包含444索暗刻，区域概率不能诱导拆刻。",
        rule="普通路线暗刻是强保护形状，除非明确特殊路线要求，不可拆。",
    ),
    StrategyReviewCase(
        case_id="random-2-turn-4-discard",
        title="摸5索后保留索子改良并切弱牌",
        source="random replay sample 2 turn 4",
        dora_id=8,
        ura_dora_id=29,
        kind="discard",
        hand=(3, 5, 10, 12, 12, 14, 21, 22, 26, 28, 28, 28, 29, 13),
        balls=6,
        drawn_tile=13,
        forbidden_choices=(12, 13),
        accepted_choices=(3, 5, 21, 22, 26, 29),
        objection="5索使索子结构前进，不能因局部目标概率立即摸切。",
        rule="远向听普通路线同时评价面子、搭子和改良，不只评价下一张目标。",
    ),
    StrategyReviewCase(
        case_id="random-2-turn-9-discard",
        title="第四张南必须直接摸切",
        source="random replay sample 2 turn 9",
        dora_id=8,
        ura_dora_id=29,
        kind="discard",
        hand=(3, 5, 10, 10, 11, 12, 12, 14, 14, 21, 28, 28, 28, 28),
        balls=1,
        drawn_tile=28,
        forbidden_choices=(21,),
        accepted_choices=(28,),
        objection="第四张相同字牌不能用于顺子，保留三张刻子即可。",
        rule="第四张字牌是强制摸切规则。",
    ),
    StrategyReviewCase(
        case_id="random-1-turn-4-question",
        title="普通路线比较1索与2万的多步改良",
        source="random replay sample 1 turn 4",
        dora_id=28,
        ura_dora_id=10,
        kind="discard",
        hand=(1, 3, 5, 6, 9, 11, 11, 12, 16, 16, 24, 25, 26, 6),
        balls=5,
        drawn_tile=6,
        forbidden_choices=(24, 25, 26),
        accepted_choices=(9,),
        objection="已无特殊路线，应比较切1索与切2万后的向听、进张和后续区域改良。",
        rule="普通效率排序为形状、向听、有效进张、区域概率。",
    ),
    StrategyReviewCase(
        case_id="random-5-turn-1-area",
        title="四张三元牌且八球时优先大三元",
        source="random replay sample 5 turn 1",
        dora_id=8,
        ura_dora_id=26,
        kind="area",
        hand=(4, 5, 14, 18, 20, 22, 28, 29, 30, 31, 32, 33, 33),
        balls=8,
        forbidden_choices=(5,),
        accepted_choices=(4,),
        objection="已有四张三元牌和红中对子；国士缺少多张低概率边牌，不应压过大三元。",
        rule="大三元缺牌数按三组龙刻子加外部一面子一雀头独立计算，满足球数时优先区域4。",
    ),
    StrategyReviewCase(
        case_id="random-6-turn-2-area",
        title="二向听时按直接进张选择区域",
        source="random replay sample 6 turn 2",
        dora_id=7,
        ura_dora_id=26,
        kind="area",
        hand=(2, 2, 6, 8, 9, 12, 12, 13, 14, 16, 17, 23, 25),
        balls=7,
        forbidden_choices=(3,),
        accepted_choices=(2,),
        objection="区域3的整门索子不能全部按一等有效牌计算；8万、7索、7饼才是直接前进牌。",
        rule="一阶进张满权重，孤张、对子或靠张改良只给较低二阶权重。",
    ),
    StrategyReviewCase(
        case_id="random-6-turn-3-area",
        title="八张索子仍不虚报整门8200权重",
        source="random replay sample 6 turn 3",
        dora_id=7,
        ura_dora_id=26,
        kind="area",
        hand=(2, 2, 6, 8, 9, 9, 12, 12, 13, 14, 16, 17, 23),
        balls=6,
        forbidden_choices=(3,),
        accepted_choices=(2,),
        objection="79万仍是完整搭子，不能仅因索子达到八张就把整门索子都当作直接进张。",
        rule="近向听且外部仍有强搭子时不强制转混一色，继续按直接进张概率选择区域。",
    ),
    StrategyReviewCase(
        case_id="random-6-turn-3-discard",
        title="索子推进后先切孤立6饼",
        source="random replay sample 6 turn 3",
        dora_id=7,
        ura_dora_id=26,
        kind="discard",
        hand=(2, 2, 6, 8, 9, 9, 11, 12, 12, 13, 14, 16, 17, 23),
        balls=5,
        drawn_tile=11,
        forbidden_choices=(6, 8),
        accepted_choices=(23,),
        objection="摸3索后不应拆79万搭子，孤立6饼是更朴素且保留后续形状的选择。",
        rule="普通效率与软同花色路线都先保护完成面子、对子和有效搭子，再比较孤张。",
    ),
    StrategyReviewCase(
        case_id="random-7-turn-1-area",
        title="远向听时允许向最多花色柔性靠拢",
        source="random replay sample 7 turn 1",
        dora_id=13,
        ura_dora_id=0,
        kind="area",
        hand=(0, 3, 4, 4, 6, 8, 11, 12, 12, 15, 17, 23, 30),
        balls=8,
        forbidden_choices=(),
        accepted_choices=(1, 2),
        objection="万字数量领先时，可以在不牺牲牌效率的前提下向万字区域靠拢。",
        rule="远向听只做柔性花色偏置；若区域2的一阶效率相当，也保留为合法选择。",
    ),
    StrategyReviewCase(
        case_id="random-10-turn-2-area",
        title="四暗刻路线只把重复牌列为直接目标",
        source="random replay sample 10 turn 2",
        dora_id=23,
        ura_dora_id=15,
        kind="area",
        hand=(1, 2, 7, 10, 10, 11, 11, 14, 14, 14, 21, 23, 25),
        balls=7,
        forbidden_choices=(),
        accepted_choices=(7,),
        objection="1万和4万能改善23万顺子，但不会直接减少四暗刻所需的对子或刻子数量。",
        rule="役满路线的主目标只计算直接减少役满缺牌数的牌；普通顺子改良作为后路，不与主目标等权。",
    ),
    StrategyReviewCase(
        case_id="random-11-turn-3-discard",
        title="四暗刻概率接近时保留索子与七对后路",
        source="random replay sample 11 turn 3",
        dora_id=33,
        ura_dora_id=1,
        kind="discard",
        hand=(3, 5, 7, 9, 9, 11, 11, 12, 12, 14, 15, 16, 16, 27),
        balls=5,
        drawn_tile=11,
        forbidden_choices=(15,),
        accepted_choices=(3,),
        objection="切7索会破坏索子清一色、混一色和七对后路；切4万的四暗刻成功率只略低。",
        rule="役满候选成功率在最佳值九成以内时，优先切弱异色孤张并保留强同花色后路。",
    ),
)
